### ISSUE TITLE
--sponsorblock-remove flag

### ISSUE THREAD

**Issue by Goldmaster** [TheFrenchGhosty/TheFrenchGhostys-Ultimate-YouTube-DL-Scripts-Collection#113]
Hi there,

Been using your scripts to archive YouTube videos. I have noticed in the description that you have SponsorBlock support via integration using [mpv_sponsorblock](https://github.com/po5/mpv_sponsorblock), however, I know yt-dlp now natively supports SponsorBlock via --sponsorblock-remove https://github.com/yt-dlp/yt-dlp?tab=readme-ov-file#sponsorblock-options, so why hasn't the scripts been updated to support SponsorBlock natively? Is it to allow for each one's personal preference?

Many thanks

**Comment by TheFrenchGhosty** [comment]
Originally, the yt-dlp SponsorBlock integration actively "removed" the content from the downloaded files.

Because those scripts are made for archival purpose and the fact the sponsors are still part of the videos, I did not want them to be removed from the videos.

Moreover, the SponsorBlock database is highly imperfect, so using it as "a source of trust" is overly risky.

---

I just discovered that `--sponsorblock-mark` is a thing, it wasn't originally. This indeed is "better" since it doesn't remove the "content", but it still depends on the SponsorBlock DB as a source of trust, also, it might conflict with videos where the YouTube creators actually mark the sponsorship in the chapters.

In the end, my script shouldn't do anything related to SponsorBlock, your client should, this is how it was always done, and how it will continue to be done for the forceable future.
