### ISSUE TITLE
[Windows] Cygwin can be used instead of WSL, much easier and more user friendly

### ISSUE THREAD

**Issue by Rings4** [TheFrenchGhosty/TheFrenchGhostys-Ultimate-YouTube-DL-Scripts-Collection#47]
Setting up WSL proved to be quite a pain, requiring you to enable a Windows feature, reboot, then essentially download and install an instance of Ubuntu in order to boot into it just to run bash scripts. 

What I find to be infinitely easier and more efficient is to simply use Cygwin. Cygwin allows you to run Linux commands in Windows as though it were being run natively. I suggest adding this under the Windows instructions and mentioning WSL as a secondary method. 

![Screenshot 2021-02-18 14 40 28](https://user-images.githubusercontent.com/32050292/108412045-544b1680-71f7-11eb-91fe-b0caa0d7e96c.png)

**Comment by TheFrenchGhosty** [comment]
I'm not experienced with anything linux-on-windows related, so feel free to open a PR about a full setup for beginners (in docs/)

**Comment by pukkandan** [comment]
While cygwin is easier to initially set up, If the user can set up WSL, I would still recommend it - especially if it's WSL2. Cygwin still has a lot of bugs/quirks.

Also, whichever method you use, I also suggest adding `--windows-filenames` to the scripts when using on windows. Some filenames will cause issues otherwise (since yt-dlp thinks it is running in UNIX and therefore doesn't clean up filenames as needed by the windows FS)

**Comment by LSchallot** [comment]
I believe that anything with bash for Windows (Cygwin, Git Bash, etc) could make use of these scripts.  I use Git Bash daily so I can write up some documentation on that setup and *hopefully* it will correspond with Cygwin.

**Comment by TheFrenchGhosty** [comment]
Done in #58
