### ISSUE TITLE
Do I have to manually figure out which videos were deleted?

### ISSUE THREAD

**Issue by github-account1111** [TheFrenchGhosty/TheFrenchGhostys-Ultimate-YouTube-DL-Scripts-Collection#65]
I like the idea of separating recents from non-recents, but I do not understand what is supposed to happen after the fact.

Say, it's been a few months, I've accumulated multiple videos, a few were deleted - let's be optimistic and say most weren't. Do I then have to go through all those videos and determine which ones can and can't be deleted and then transfer whichever ones remain into their respective folders?

If the answer is yes, that's quite cumbersome and error-prone.

If not, is there some functionality inside the script that takes care of this?

**Comment by TheFrenchGhosty** [comment]
Yes, and yes it's not ideal.

**Comment by 93-infinity** [comment]
I'm also interested in this, but I don't fully understand what you're asking.

Are you saying this is your situation? (Let's assume only one video per year, named exactly as thus, for simplicity's sake)

| Archivist| Recent |
| ----------- | ----------- |
| ----      | 2021       |
| 2020   | 2020        |
| ----      | 2019       |
| 2018   | 2018        |

For example, 2021 is still too recent to be archived. 2020 and 2018 have not been deleted so the "recent" can assumed to be inferior to the "archivist" version. 2019 has obviously been deleted within a month since it only exists in "recent" and "archivist" did not catch it. Obviously side-by-side it's easy to see 2019 has been deleted, but, are you are saying:

1) it's hard to determine if 2019 should be moved,
2) you are afraid you might accidentally move 2018 recent->archive, replacing a high quality version with an inferior version?

**Comment by github-account1111** [comment]
Yes, nicely put. It's both. Both can happen, and both would be undesirable. It's easy to determine side-by-side what should happen in your example, but, like you said, it's a simplified version of what is likely going to happen.

Having a check in place every time the script runs to move what can be moved (2019), keep what is still too recent (2021) and delete what has been archived (2020 and 2018) would be nice.

**Comment by jacroe** [comment]
@TheFrenchGhosty It's the only automated way I can think of that will get some version of a copy of everything as it's posted.

So definitely complicated. And definitely slower since it's running through everything twice. But does that matter? It's a robot; tedious things are exactly what they're made for :robot:

**Comment by TheFrenchGhosty** [comment]
A script has been written and will be released soon.

**Comment by jacroe** [comment]
@TheFrenchGhosty Did the script get released? I couldn't immediately find it if it did, and I just wanted to make sure I didn't miss it. No worries at all if it didn't

**Comment by TheFrenchGhosty** [comment]
@jacroe It hasn't been released no... and I don't remember where I put it... oops.

(I almost certainly still have it somewhere in my archive)

**Comment by TheFrenchGhosty** [comment]
@jacroe Found it in my archive, here it is:


[youtubeavailable.sh.zip](https://github.com/TheFrenchGhosty/TheFrenchGhostys-Ultimate-YouTube-DL-Scripts-Collection/files/14232917/youtubeavailable.sh.zip)



Note: it's an highly experimental version that worked when I tested it back then, I haven't used it since I made it back in august 2023 so it might be highly imperfect. 

If I remember correct, you have to run it in the folder where the "channel name" folders are. The list of unavailable videos will be outputted to unavailable_videos.txt
